# Generated by Django 3.0.5 on 2020-10-02 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelance', '0002_ticket_ticket_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exectuor',
            new_name='Executor',
        ),
    ]
