# Generated by Django 3.0.5 on 2020-10-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0004_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='FreelanceAuthoring',
        ),
        migrations.DeleteModel(
            name='FreelanceCustomer',
        ),
        migrations.DeleteModel(
            name='FreelanceExecutor',
        ),
        migrations.DeleteModel(
            name='FreelanceMessage',
        ),
        migrations.DeleteModel(
            name='FreelanceOrder',
        ),
        migrations.DeleteModel(
            name='FreelanceOrdering',
        ),
        migrations.DeleteModel(
            name='FreelanceReview',
        ),
        migrations.DeleteModel(
            name='FreelanceService',
        ),
        migrations.DeleteModel(
            name='FreelanceTag',
        ),
        migrations.DeleteModel(
            name='FreelanceTicket',
        ),
    ]
